"""Load the generated routes manifests + static-route policies (RFC-07).

Replaces the live k8s discovery + signed-bundle cedar sources: routing metadata
now ships as ConfigMap-mounted YAML files generated by the commons
OpenApiAuthPreprocessor (`--routes-output`). The authorization decision is made
by the central Cerbos PDP; these loaders only build the path→operation table.
"""
import logging
import os
from typing import Dict, List

import yaml

from policy_store import RoutePolicy, StaticPolicy, compile_template

logger = logging.getLogger("traefik_authproxy.routes_loader")


def load_routes_dir(routes_dir: str) -> Dict[str, List[RoutePolicy]]:
    """Parse every ``*.yaml`` routes manifest in ``routes_dir``.

    Each manifest has ``version/module/basePath/routes``; a route's external
    template is ``basePath + route.path``. A malformed file is logged and
    skipped (fail closed: its routes simply don't exist → 403). Returns
    {module: [RoutePolicy, ...]}.
    """
    modules: Dict[str, List[RoutePolicy]] = {}
    if not routes_dir or not os.path.isdir(routes_dir):
        logger.warning("routes dir %s missing — no module routes loaded", routes_dir)
        return modules
    for name in sorted(os.listdir(routes_dir)):
        if not (name.endswith(".yaml") or name.endswith(".yml")):
            continue
        path = os.path.join(routes_dir, name)
        try:
            with open(path, "r") as f:
                doc = yaml.safe_load(f)
            module = doc["module"]
            base_path = (doc.get("basePath") or "").rstrip("/")
            routes: List[RoutePolicy] = []
            for r in doc.get("routes") or []:
                operation_id = r.get("operationId") or f'{r["method"]}:{r["path"]}'
                template = base_path + r["path"]
                routes.append(RoutePolicy(
                    module=module,
                    operation_id=operation_id,
                    method=str(r["method"]).upper(),
                    path_template=template,
                    public=bool(r.get("public")),
                    tenant_required=bool(r.get("tenantRequired")),
                    scopes=tuple(r.get("scopes") or ()),
                    pattern=compile_template(template),
                ))
            modules[module] = routes
        except Exception as e:  # noqa: BLE001 — a broken manifest must not take down others
            logger.error("routes manifest %s failed to load — skipping: %s", name, e)
    return modules


def load_static_routes(file_path: str) -> List[StaticPolicy]:
    """Parse the static-route policies for surfaces without an OpenAPI spec.

    YAML shape: ``static: [{id, prefix, public, scopes}]``. Missing/malformed
    file → empty list (fail closed).
    """
    if not file_path or not os.path.isfile(file_path):
        return []
    try:
        with open(file_path, "r") as f:
            doc = yaml.safe_load(f) or {}
    except Exception as e:  # noqa: BLE001
        logger.error("static routes file %s failed to load: %s", file_path, e)
        return []
    policies: List[StaticPolicy] = []
    for entry in doc.get("static") or []:
        prefix = entry.get("prefix")
        if not prefix:
            continue
        policies.append(StaticPolicy(
            prefix=prefix,
            public=bool(entry.get("public")),
            scopes=tuple(entry.get("scopes") or ()),
            static_id=entry.get("id", ""),
        ))
    return policies
